using SpiceSharp.Attributes;
using SpiceSharpBSIM.Components.Semiconductors.BSIM.BSIM3Behaviors;
using SpiceSharp.Entities;

namespace SpiceSharp.Components
{
    /// <summary>
    /// Model for the <see cref="BSIM3"/> component
    /// </summary>
    [AutoGeneratedBehaviors]
    public partial class BSIM3Model : Entity<ModelParameters>
    {
        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="name">Name</param>
        public BSIM3Model(string name)
            : base(name)
        {
        }
    }
}
