using SpiceSharp.Entities;
using SpiceSharpBSIM.Components.Semiconductors.BSIM.BSIM4Behaviors;
using SpiceSharp.Attributes;

namespace SpiceSharp.Components
{
    /// <summary>
    /// 
    /// </summary>
    [AutoGeneratedBehaviors]
    public partial class BSIM4Model : Entity<ModelParameters>
    {
        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="name">Name</param>
        public BSIM4Model(string name)
            : base(name)
        {
        }
    }
}
