using SpiceSharp.Attributes;
using SpiceSharp.Components;
using SpiceSharpBSIM.Components.Semiconductors.BSIM.BSIM4Behaviors;
using System;
using System.Collections.Generic;
using System.Text;

namespace SpiceSharp.Components
{
    /// <summary>
    /// A BSIM4 component.
    /// </summary>
    [Pin(0, "drain"), Pin(1, "gate"), Pin(2, "source"), Pin(3, "bulk"), Connected(0, 2)]
    [AutoGeneratedBehaviors]
    public partial class BSIM4 : Component<BaseParameters>
    {
        /// <summary>
        /// Number of pins
        /// </summary>
        [ParameterName("pincount"), ParameterInfo("Number of pins")]
        public const int BSIM4PinCount = 4;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="name">Name</param>
        public BSIM4(string name)
            : base(name, BSIM4PinCount)
        {
        }

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="name">Name</param>
        /// <param name="drain">Drain</param>
        /// <param name="gate">Gate</param>
        /// <param name="source">Source</param>
        /// <param name="bulk">Bulk</param>
        public BSIM4(string name, string drain, string gate, string source, string bulk)
            : this(name)
        {
            Connect(drain, gate, source, bulk);
        }

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="name">Name</param>
        /// <param name="drain">Drain</param>
        /// <param name="gate">Gate</param>
        /// <param name="source">Source</param>
        /// <param name="bulk">Bulk</param>
        /// <param name="width">Transistor width</param>
        /// <param name="length">Transistor length</param>
        public BSIM4(string name, string drain, string gate, string source, string bulk, double width, double length)
            : this(name)
        {
            Parameters.W = width;
            Parameters.L = length;
            Connect(drain, gate, source, bulk);
        }
    }
}
