using SpiceSharp.Attributes;
using SpiceSharp.Entities;
using System.Collections.Generic;

namespace SpiceSharp.Components
{
    /// <summary>
    /// An aggregate for <see cref="BSIM4Model"/> that have
    /// different lmin/lmax/wmin/wmax parameters.
    /// </summary>
    [AutoGeneratedBehaviors]
    public partial class BSIM4AggregateModel : Entity
    {
        /// <summary>
        /// Gets the models in the aggregate model based on sizes.
        /// </summary>
        public HashSet<BSIM4Model> Models { get; } = [];

        /// <summary>
        /// Creates an aggregate model.
        /// </summary>
        /// <param name="name">The name.</param>
        public BSIM4AggregateModel(string name)
            : base(name)
        {
        }

        /// <summary>
        /// Creates an aggregate model based on sizes.
        /// </summary>
        /// <param name="name"></param>
        /// <param name="models"></param>
        public BSIM4AggregateModel(string name, IEnumerable<BSIM4Model> models)
            : base(name)
        {
            foreach (var model in models)
                Models.Add(model);
        }

        /// <inheritdoc />
        public override IEntity Clone()
        {
            var n = new BSIM4AggregateModel(Name);
            foreach (var model in Models)
                n.Models.Add((BSIM4Model)model.Clone());
            return n;
        }
    }
}
