using SpiceSharp.Attributes;
using SpiceSharp.Entities;
using SpiceSharpBSIM.Components.Semiconductors.BSIM.BSIM2Behaviors;

namespace SpiceSharp.Components
{
    /// <summary>
    /// Model for the <see cref="BSIM2"/> component
    /// </summary>
    [AutoGeneratedBehaviors]
    public partial class BSIM2Model : Entity<ModelParameters>
    {
        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="name">Name</param>
        public BSIM2Model(string name)
            : base(name)
        {
        }
    }
}