name: Linux Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    
    - name: Setup dotnet tooling
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Compile Spice#.BSIM
      run: dotnet build SpiceSharpBSIM/SpiceSharpBSIM.csproj --configuration Debug --no-restore

    - name: Compile Spice#.BSIM.Tests
      run: dotnet test SpiceSharpBSIMTests/SpiceSharpBSIMTests.csproj --configuration Debug --no-restore
